#@ load("@ytt:data", "data")

#@ def pipeline_image():
#@   return data.values.docker_registry + "/galoy-deployments-pipeline"
#@ end

#@ def task_image_config():
type: registry-image
source:
  username: #@ data.values.docker_registry_user
  password: #@ data.values.docker_registry_password
  repository: #@ pipeline_image()
#@ end

#@ def repo_pr_branch_resource_name(repo_name):
#@   return repo_name + "-pr-branch"
#@ end

#@ def repo_resource_name(repo_name):
#@   return repo_name + "-repo"
#@ end

groups:
- name: bump-shared-files
  jobs:
#@ for repo in data.values.src_repos:
  - #@ "bump-shared-files-in-" + repo
#@ end
- name: images
  jobs:
  - build-nodejs-concourse-image

jobs:
- name: build-nodejs-concourse-image
  serial: true
  plan:
  - {get: nodejs-image-def, trigger: true}
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: nodejs-image-def
      outputs:
      - name: image
      params:
        CONTEXT: nodejs-image-def/images/nodejs-concourse
      run:
        path: build
  - put: nodejs-image
    params:
      image: image/image.tar

#@ for repo in data.values.src_repos:
- name: #@ "bump-shared-files-in-" + repo
  plan:
  - in_parallel:
    - { get: shared-files, trigger: true }
    - { get: pipeline-tasks }
    - get: #@ repo_resource_name(repo)
  - task: #@ "bump-shared-files-" + repo
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: shared-files
        path: repo
      - name: pipeline-tasks
      - name: #@ repo_resource_name(repo)
        path: source-repo
      outputs:
      - name: source-repo
      run:
        path: pipeline-tasks/ci/tasks/bump-shared-files.sh
  - put: #@ repo_pr_branch_resource_name(repo)
    params:
      repository: source-repo
      force: true
  - task: open-source-pr
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: pipeline-tasks
      - name: #@ repo_resource_name(repo)
        path: source-repo
      params:
        PR_BRANCH: #@ data.values.pr_branch
        BRANCH: #@ data.values.source_repo_branch
        GH_TOKEN: #@ data.values.github_token
      run:
        path: pipeline-tasks/ci/tasks/open-pr.sh
#@ end

resources:
- name: shared-files
  type: git
  source:
    paths:
    - shared/**/*
    - shared/*
    - vendir.tmpl.yml
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

- name: pipeline-tasks
  type: git
  source:
    paths: [ci/tasks/*, Makefile]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

#@ for repo in data.values.src_repos:
- name: #@ repo_pr_branch_resource_name(repo)
  type: git
  source:
    uri: #@ data.values.git_org_uri + "/" + repo + ".git"
    private_key: #@ data.values.github_private_key
    branch: #@ data.values.pr_branch
#@ end

#@ for repo in data.values.src_repos:
- name: #@ repo_resource_name(repo)
  type: git
  source:
    uri: #@ data.values.git_org_uri + "/" + repo + ".git"
    private_key: #@ data.values.github_private_key
    branch: #@ data.values.source_repo_branch
#@ end

- name: nodejs-image-def
  type: git
  source:
    paths: [images/nodejs-concourse/Dockerfile]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

- name: nodejs-image
  type: registry-image
  source:
    tag: latest
    username: #@ data.values.docker_registry_user
    password: #@ data.values.docker_registry_password
    repository: #@ data.values.docker_registry + "/nodejs-concourse"
