#@data/values
---

git_uri: git@github.com:GaloyMoney/concourse-shared.git
git_branch: main
github_private_key: ((github.private_key))
github_token: ((github.api_token))
github_app_id: ((github.github_app_id))
github_app_private_key: ((github.github_app_private_key))

docker_registry: us.gcr.io/galoy-org
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))

git_org_uri: git@github.com:GaloyMoney
pr_branch: bump-shared-tasks
source_repo_branch: main

src_repos:
  galoy: ["nodejs", "docker", "chart"]
  stablesats-rs: ["rust", "docker", "chart"]
  proof-of-sats: ["nodejs", "docker", "chart"]
  galoy-cli: ["rust"]
  sqlx-ledger: ["rust", "docker"]
  sqlxmq-executor: ["rust", "docker"]
  bria: ["rust", "docker", "chart"]
  galoy-mobile: ["nodejs"]
  blink-circles: ["nodejs", "docker", "chart"]
  blink-fiat: ["nodejs", "docker", "chart"]
  blink-kyc: ["nodejs", "docker", "chart"]
  post-print-companion: ["nodejs"]
