#@data/values
---

git_uri: git@github.com:GaloyMoney/concourse-shared.git
git_branch: main
github_private_key: ((github.private_key))
github_token: ((github.api_token))

docker_registry: us.gcr.io/galoy-org
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))

git_org_uri: git@github.com:GaloyMoney
pr_branch: bump-shared-tasks
source_repo_branch: main

src_repos:
  galoy: ["nodejs", "docker", "chart"]
  admin-panel: ["nodejs", "docker", "chart"]
  galoy-pay: ["nodejs", "docker", "chart"]
  stablesats-rs: ["rust", "docker", "chart"]
  galoy-client: ["nodejs", "docker", "chart"]
  galoy-react: ["nodejs", "docker", "chart"]
  web-wallet: ["nodejs", "docker", "chart"]
  proof-of-sats: ["nodejs", "docker", "chart"]
  galoy-cli: ["rust"]
  sqlx-ledger: ["rust", "docker"]
  sqlxmq-executor: ["rust", "docker"]
